### ISSUE TITLE
remove this obsolete app from apps.nextcloud.com please

### ISSUE THREAD

**Issue by p-bo** [fgsl/initialcheck#5]
Hello,
would it be possible to follow instructions on:

https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app

and remove your past app:

https://apps.nextcloud.com/apps/githubmergetracker

and help through this to tidy up the Nextcloud App store (most importantly it clutters apps catalogue in every Nextcloud instance) a bit please?

Thanks and have a nice day

**Comment by fgsl** [comment]
> Hello, would it be possible to follow instructions on:
> 
> https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app
> 
> and remove your past app:
> 
> https://apps.nextcloud.com/apps/githubmergetracker
> 
> and help through this to tidy up the Nextcloud App store (most importantly it clutters apps catalogue in every Nextcloud instance) a bit please?
> 
> Thanks and have a nice day

Hi, @p-bo. I have run  `curl -X DELETE https://apps.nextcloud.com/api/v1/apps/initialcheck`.

However, I didn't understand what I should do about this URL https://apps.nextcloud.com/apps/githubmergetracker, since it is an app by Lukas Reschke.

**Comment by p-bo** [comment]
@fgsl sorry, forgot to edit link it should be https://apps.nextcloud.com/apps/initialcheck (now wiped out)

Thanks for cooperation!
